// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RihalAssesment.Data;

namespace RihalAssesment.Migrations
{
    [DbContext(typeof(StudentDbContext))]
    [Migration("20220926083756_Inital-Commit")]
    partial class InitalCommit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("RihalAssesment.Data.Students", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("class_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("country_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("date_of_birth")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Student");

                    b.HasData(
                        new
                        {
                            id = 1001,
                            class_id = 1,
                            country_id = 1,
                            date_of_birth = "25-06-1991",
                            name = "Anoob"
                        });
                });

            modelBuilder.Entity("RihalAssesment.Data.classes", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("class_name")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            id = 1,
                            class_name = "First Standard"
                        });
                });

            modelBuilder.Entity("RihalAssesment.Data.country", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("country_name")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Country");

                    b.HasData(
                        new
                        {
                            id = 101,
                            country_name = "India"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
